# Generated by Django 4.2.13 on 2024-07-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deficiency', '0003_alter_deficiency_options_and_more'),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deficiency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deficiency.deficiency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RemedyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.remedy')),
            ],
            options={
                'unique_together': {('remedy', 'food')},
            },
        ),
    ]
