# Generated by Django 4.2.13 on 2024-07-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remedy',
            options={'verbose_name_plural': 'Remedies'},
        ),
    ]
