# Generated by Django 4.2.13 on 2024-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0002_alter_remedy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='scientific_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
