# Generated by Django 4.2.13 on 2024-08-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('underweight', 'Underweight'), ('normal', 'Normal weight'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('athlete', 'Athlete')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('days', models.IntegerField()),
                ('health_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.healthstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_meals', to='meal.mealplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DayMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.IntegerField(default=1)),
                ('afternoon_snack', models.ManyToManyField(blank=True, related_name='afternoon_snacks', to='meal.meal')),
                ('breakfast', models.ManyToManyField(related_name='breakfast_meals', to='meal.meal')),
                ('dinner', models.ManyToManyField(related_name='dinner_meals', to='meal.meal')),
                ('evening_snack', models.ManyToManyField(blank=True, related_name='evening_snacks', to='meal.meal')),
                ('lunch', models.ManyToManyField(related_name='lunch_meals', to='meal.meal')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_meals', to='meal.mealplan')),
                ('mid_morning_snack', models.ManyToManyField(blank=True, related_name='mid_morning_snacks', to='meal.meal')),
            ],
            options={
                'unique_together': {('meal_plan', 'day_number')},
            },
        ),
    ]
