# Generated by Django 4.2.13 on 2024-08-26 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlymealplan',
            name='meal_plan',
        ),
        migrations.DeleteModel(
            name='DayMealPlan',
        ),
        migrations.DeleteModel(
            name='MonthlyMealPlan',
        ),
    ]
