# Generated by Django 4.2.13 on 2024-08-26 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_remove_monthlymealplan_meal_plan_delete_daymealplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.IntegerField(default=1)),
                ('afternoon_snack', models.ManyToManyField(blank=True, related_name='afternoon_snacks', to='meal.meal')),
                ('breakfast', models.ManyToManyField(related_name='breakfast_meals', to='meal.meal')),
                ('dinner', models.ManyToManyField(related_name='dinner_meals', to='meal.meal')),
                ('evening_snack', models.ManyToManyField(blank=True, related_name='evening_snacks', to='meal.meal')),
                ('lunch', models.ManyToManyField(related_name='lunch_meals', to='meal.meal')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_meals', to='meal.mealplan')),
                ('mid_morning_snack', models.ManyToManyField(blank=True, related_name='mid_morning_snacks', to='meal.meal')),
            ],
            options={
                'unique_together': {('meal_plan', 'day_number')},
            },
        ),
    ]
