# Generated by Django 4.2.13 on 2024-08-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_daymealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='health_status',
        ),
        migrations.DeleteModel(
            name='DayMealPlan',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
