# Generated by Django 4.2.13 on 2024-08-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_mealplan_daymealplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daymealplan',
            name='afternoon_snack',
        ),
        migrations.RemoveField(
            model_name='daymealplan',
            name='breakfast',
        ),
        migrations.AlterField(
            model_name='daymealplan',
            name='day_number',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='daymealplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='daymealplan',
            name='evening_snack',
        ),
        migrations.RemoveField(
            model_name='daymealplan',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='daymealplan',
            name='mid_morning_snack',
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='afternoon_snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afternoon_snacks', to='meal.meal'),
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_meals', to='meal.meal'),
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dinner_meals', to='meal.meal'),
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='evening_snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evening_snacks', to='meal.meal'),
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_meals', to='meal.meal'),
        ),
        migrations.AddField(
            model_name='daymealplan',
            name='mid_morning_snack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_morning_snacks', to='meal.meal'),
        ),
    ]
