# Generated by Django 4.2.13 on 2024-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0010_usermealplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daymealcompletion',
            name='date',
            field=models.DateField(),
        ),
    ]
