# Generated by Django 4.2.13 on 2024-08-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_usermealplan_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstatus',
            name='status',
            field=models.CharField(choices=[('underweight', 'Underweight'), ('wasted', 'Wasted'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('stunted', 'Stunted')], max_length=20, unique=True),
        ),
    ]
