# Generated by Django 4.2.13 on 2024-09-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0014_alter_healthstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='health_status_info',
            field=models.CharField(choices=[('underweight', 'Underweight'), ('wasted', 'Wasted'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('stunted', 'Stunted')], default='wasted', max_length=20),
        ),
    ]
