# Generated by Django 4.2.13 on 2024-09-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0016_remove_usermealplan_health_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='health_status',
        ),
        migrations.AddField(
            model_name='meal',
            name='health_status_info',
            field=models.CharField(choices=[('underweight', 'Underweight'), ('wasted', 'Wasted'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('stunted', 'Stunted')], default='wasted', max_length=20),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='health_status_info',
            field=models.CharField(choices=[('underweight', 'Underweight'), ('wasted', 'Wasted'), ('overweight', 'Overweight'), ('obese', 'Obese'), ('stunted', 'Stunted')], default='wasted', max_length=20),
        ),
    ]
