# Generated by Django 4.2.13 on 2024-07-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
