# Generated by Django 4.2.13 on 2024-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_vitamin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='scientificName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
